### ISSUE TITLE
BugFix: Snackbar shows wrong value in admin page

### ISSUE THREAD

**Issue by Lauri-Iivarinen** [LibraryProjectGroup/library-project-frontend#173]
When editing user data as admin the snackbar that announces if the action was successfull always indicates that the action was succesfull. For example while editing user if home office is left unfilled the form is not submitted but the message says user was edited.

**Comment by laurireis** [comment]
![image](https://github.com/LibraryProjectGroup/library-project-frontend/assets/94443029/b93aeca0-e0b2-48a0-9afc-dfe8db9303d3)
The office-field isn't pre-filled in the edit form because it doesn't come in the payload of `fetchUserById()` here: [UsersGrid.tsx](https://github.com/LibraryProjectGroup/library-project-frontend/blob/main/src/components/pages/adminPage/UsersGrid.tsx#L151)

**Comment by Lauri-Iivarinen** [comment]
Fixing that can also help making testing easier, good insight!

**Comment by wilbuuuur** [comment]
office id is added to fetchUserById() response

**Comment by laurireis** [comment]
> ![image](https://user-images.githubusercontent.com/94443029/270442411-b93aeca0-e0b2-48a0-9afc-dfe8db9303d3.png) The office-field isn't pre-filled in the edit form because it doesn't come in the payload of `fetchUserById()` here: [UsersGrid.tsx](https://github.com/LibraryProjectGroup/library-project-frontend/blob/main/src/components/pages/adminPage/UsersGrid.tsx#L151). Kind of unrelated to the actual issue but fixing this would end any partial edits and help with form validation.

b9b9503 Fixed this

**Comment by laurireis** [comment]
b9b9503 Fixed the edit field being incomplete. Now the admin can't update the user without changing some values.
